import streamlit as st
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import os
import numpy as np

# --- Page Config ---
st.set_page_config(page_title="Ethiopia FI Forecast 2027", layout="wide", page_icon="🇪🇹")

# --- Custom CSS for Metric Cards ---
st.markdown("""
<style>
div.stMetric {
    background-color: #f0f2f6;
    border: 1px solid #e6e9ef;
    padding: 15px;
    border-radius: 10px;
}
</style>
""", unsafe_allow_html=True)

# --- Data Loading Helper ---
@st.cache_data
def load_data():
    # Use the processed data from previous tasks
    data_path = 'data/processed/ethiopia_fi_enriched.csv'
    forecast_path = 'data/processed/forecasting_results.csv' # using the one generated by task4
    matrix_path = 'data/processed/event_indicator_matrix.csv'
    
    # Check if files exist - forecast might be named differently in previous steps
    # Task 4 saved to 'data/processed/forecasting_results.csv'
    
    if not os.path.exists(data_path):
        return None, None, None

    # 1. Load the main enriched dataset
    df = pd.read_csv(data_path)
    if 'year' not in df.columns:
        df['observation_date'] = pd.to_datetime(df['observation_date'], errors='coerce')
        df['year'] = df['observation_date'].dt.year
    df = df.dropna(subset=['year', 'value_numeric'])
    df['year'] = df['year'].astype(int)

    # 2. Load Forecast
    if os.path.exists(forecast_path):
        df_forecast = pd.read_csv(forecast_path)
    else:
        df_forecast = pd.DataFrame()

    # 3. Load Matrix
    if os.path.exists(matrix_path):
        df_matrix = pd.read_csv(matrix_path, index_col=0)
    else:
        df_matrix = pd.DataFrame()
    
    return df, df_forecast, df_matrix

df, df_forecast, df_matrix = load_data()

if df is None:
    st.error("⚠️ Missing 'ethiopia_fi_enriched.csv'. Please run the pipeline.")
    st.stop()

# --- Sidebar ---
st.sidebar.title("Navigation")
st.sidebar.image("https://img.icons8.com/color/96/ethiopia.png", width=100)
page = st.sidebar.radio("Go to", ["Overview", "Forecast Scenarios", "Event Analysis"])

# --- Page 1: Overview ---
if page == "Overview":
    st.title("🇪🇹 Ethiopia Financial Inclusion Dashboard")
    st.markdown("Monitoring the path to NFIS-II targets.")
    
    # Metrics
    try:
        # Get latest available data (likely 2024 projection or actual)
        latest_year = df['year'].max()
        
        # Access
        acc_vals = df[df['indicator_code'] == 'ACC_OWNERSHIP'].sort_values('year')
        current_acc = acc_vals.iloc[-1]['value_numeric'] if not acc_vals.empty else 0
        delta_acc = current_acc - acc_vals.iloc[-2]['value_numeric'] if len(acc_vals) > 1 else 0
        
        # Usage (Digital Payments)
        usg_vals = df[df['indicator_code'] == 'USG_DIGITAL_ADOPTION'].sort_values('year')
        # If USG_DIGITAL_ADOPTION not found, try finding something else or 0
        if usg_vals.empty:
             usg_vals = df[df['pillar'] == 'usage'].sort_values('year')
             
        current_usg = usg_vals.iloc[-1]['value_numeric'] if not usg_vals.empty else 0
        delta_usg = current_usg - usg_vals.iloc[-2]['value_numeric'] if len(usg_vals) > 1 else 0
        
    except Exception as e:
        current_acc, delta_acc = 0, 0
        current_usg, delta_usg = 0, 0
        st.error(f"Error calculating metrics: {e}")

    col1, col2, col3 = st.columns(3)
    col1.metric("Account Ownership", f"{current_acc:.1f}%", f"{delta_acc:+.1f}pp")
    col2.metric("Digital Payment Usage", f"{current_usg:.1f}%", f"{delta_usg:+.1f}pp")
    col3.metric("NFIS-II Target (2027)", "60%", "Goal")
    
    st.divider()
    
    # Simple Trend Chart
    st.subheader("Trends at a Glance")
    indicators = st.multiselect("Select Indicators", df['indicator_code'].unique(), default=['ACC_OWNERSHIP'])
    if indicators:
        temp_df = df[df['indicator_code'].isin(indicators)]
        fig = px.line(temp_df, x='year', y='value_numeric', color='indicator_code', markers=True)
        st.plotly_chart(fig, use_container_width=True)

# --- Page 2: Forecast Scenarios ---
elif page == "Forecast Scenarios":
    st.title("🔮 2027 Forecasting & Scenarios")
    
    col_settings, col_viz = st.columns([1, 3])
    
    with col_settings:
        st.subheader("Scenario Settings")
        
        # Scenario Logic
        # 1. Select Base Scenario
        scenario_mode = st.radio("Base Assumption", ["Base", "Optimistic", "Pessimistic", "Custom"])
        
        multiplier = 1.0
        if scenario_mode == "Optimistic":
            multiplier = 1.2
        elif scenario_mode == "Pessimistic":
            multiplier = 0.5
        elif scenario_mode == "Custom":
            multiplier = st.slider("Event Impact Multiplier", 0.0, 2.0, 1.0, 0.1)
            
        st.caption(f"Applied Multiplier: **{multiplier}x**")
        st.info("Adjusts the impact of upcoming events (Interoperability, Digital ID) on the baseline trend.")

    with col_viz:
        # Check if we have pre-computed forecasts
        if df_forecast.empty:
             st.warning("No pre-computed forecasts found. Using dynamic simulation.")
             # Dynamic Simulation Logic (Simple implementation for demo)
             years = [2024, 2025, 2026, 2027]
             
             # Start from last actual
             start_val = df[df['indicator_code'] == 'ACC_OWNERSHIP']['value_numeric'].max()
             if pd.isna(start_val): start_val = 50
             
             trend_growth = 1.5 # base organic growth
             shock_impact = 3.0 * multiplier # annual shock impact
             
             forecast_vals = []
             curr = start_val
             for y in years:
                 if y > 2024:
                     curr += trend_growth + shock_impact
                 forecast_vals.append(curr)
                 
             viz_df = pd.DataFrame({'Year': years, 'Access_Rate': forecast_vals})
             
        else:
            # Filter existing forecast if available, or just modify 'Base'
            # Note: The task said "toggle between Optimistic and Pessimistic".
            # If Custom, we might need to interpolate.
            # Simplified: Display the selected pre-computed one or interpolate.
            
            if scenario_mode in ["Base", "Optimistic", "Pessimistic"]:
                viz_df = df_forecast[df_forecast['Scenario'] == scenario_mode].copy()
            else:
                # Custom: Scaled version of Base
                base = df_forecast[df_forecast['Scenario'] == 'Base'].copy()
                # Simple logic: Scale the growth from 2024
                # This is an approximation since we don't have the raw model here
                 # But it highlights "Interactivity"
                base['growth'] = base['Predicted_Ownership'].diff().fillna(0)
                # Apply multiplier to growth (assuming growth = trend + shock)
                # This is a bit hacky but works for UI demo
                base.loc[base['Year'] > 2024, 'Predicted_Ownership'] = \
                    base.loc[base['Year'] == 2024, 'Predicted_Ownership'].values[0] + \
                    (base['Predicted_Ownership'] - base.loc[base['Year'] == 2024, 'Predicted_Ownership'].values[0]) * multiplier
                viz_df = base
        
        # Plot
        fig = px.line(viz_df, x="Year", y="Predicted_Ownership", markers=True, 
                      title=f"Forecasted Account Ownership ({scenario_mode})",
                      range_y=[0, 100])
        st.plotly_chart(fig, use_container_width=True)
        
        # Policy Recommendation Logic
        final_val = viz_df.iloc[-1]['Predicted_Ownership'] if 'Predicted_Ownership' in viz_df.columns else viz_df.iloc[-1]['Access_Rate']
        target = 60.0
        
        st.subheader("Policy Recommendation")
        if final_val >= target:
            st.success(f"✅ **On Track:** Projected {final_val:.1f}% exceeds the 60% target.")
            st.write("Maintain current rollout momentum. Focus on **Quality of Usage** (depth) rather than just access.")
        else:
            gap = target - final_val
            st.error(f"🚨 **Off Track:** Projected {final_val:.1f}% misses the 60% target by {gap:.1f}pp.")
            st.markdown("### ⚠️ Interventions Needed:")
            st.markdown("- **Accelerate Fayda ID:** Ensure rural enrollment centers are active.")
            st.markdown("- **Stimulate Usage:** Introduce tax incentives for merchant digital payments.")

# --- Page 3: Event Analysis ---
elif page == "Event Analysis":
    st.title("🧩 Event Association Matrix")
    
    st.write("Heatmap showing the estimated impact of key events on financial indicators.")
    
    if not df_matrix.empty:
        fig_heat = px.imshow(df_matrix, 
                            labels=dict(x="Indicator", y="Event", color="Impact"),
                            text_auto=True,
                            aspect="auto",
                            color_continuous_scale="RdBu_r") # Red to Blue (Negative to Positive)
        st.plotly_chart(fig_heat, use_container_width=True)
    else:
        st.warning("Matrix data not found.")